### ISSUE TITLE
Student screen (Quiz interaction) - Frontend 

### ISSUE THREAD

**Issue by Annanyuan** [deco3500-2019/Apple_Pen#13]
# Description
After group discussion, we built a prototype in students' version by using Figma. In this version, the graphic design is more simple and clearer and consistent with the final product we expect to build. The quiz interaction in students' screen has the abilities below:
* Waiting for questions released by teacher;
* Checking questions;
* Selecting answer;
* Time limitation notification;
* Receiving feedback of the answers.

We are going to program the layout based on the prototype. (Prototype link: https://www.figma.com/proto/jniZkKkOKAcr6rycUOIAYf/Quiz_room?node-id=1%3A2&scaling=scale-down)

**TODO**:
- [ ] Show count down

**Comment by scottgullaksen** [comment]
### TODO
- [ ] Show timer count down
