### ISSUE TITLE
Analize raw data

### ISSUE THREAD

**Issue by scottgullaksen** [deco3500-2019/Apple_Pen#3]
After the data gathering from our research methods (#1, #2) we need to figure out the key themes that our users highlight. This will be valuable when we try to generate idead

**Comment by akajenny** [comment]
We did a card-sorting-session where we grouped the cards in categories (specified by the markers). Below are the results. Check out #4 to see how we advanced on this to generate specific ideas.
![WechatIMG239](https://user-images.githubusercontent.com/54489989/66455968-9b77b200-eaaf-11e9-8958-1f767293ef69.jpeg)
![Uploading WechatIMG240.jpeg…]()
